### ISSUE TITLE
White Icons

### ISSUE THREAD

**Issue by ProLoser** [webdog/octicons-png#2]
Would love to have a set in white, don't know how you created this set.

**Comment by trevor-coleman** [comment]
+1!

**Comment by trevor-coleman** [comment]
@ProLoser: I ended up making this myself: https://github.com/trevor-coleman/octicons-black-and-white-png

@webdog: I tried to make a PR, but I couldn't push the changes. Happy to contribute here, or feel free to copy them over yourself!

**Comment by webdog** [comment]
@trevor-coleman Thanks! My notifications were off for this repo aside from direct mentions, so I missed this. Notifications are now on, appreciate the help in contributing ✨ 

Happy to accept a PR! From the PR UI in this repo you should be able to set your fork as the base, and my repo as the upstream to merge into.

![image](https://user-images.githubusercontent.com/960210/38876133-82b23804-4221-11e8-862d-7e540c74dd64.png)

**Comment by trevor-coleman** [comment]
OK awesome! Will do that now! 

This is my first ever open source contribution! Huzzah! 🎉
