### ISSUE TITLE
File naming scheme

### ISSUE THREAD

**Issue by trevor-coleman** [webdog/octicons-png#4]
So currently the pngs are all organized like this:

`./${color}/${icon_name}.svg.png`

for example `./white/arrow-small-up.svg.png`

I was thinking I could remove the .svg from .svg.png and reupload.

At the same time, would be better to include the colour in the filename?

e.g. `opticons-png/white/arrow-small-up-white.png` 

We could use the [x11 color names](https://en.wikipedia.org/wiki/Web_colors#X11_color_names) as a standard.

I could write a bash script to automate the process at the same time, so people could render arbitrary colours as needed.

**Comment by webdog** [comment]
@trevor-coleman Yeah, those *svg.png were an artificat of the converter I originally used. I can fix that with a PR here in a few minutes.

👍 on the naming convention

**Comment by trevor-coleman** [comment]
Nice — yeah I had the same thing. Did you use `rsvg`?

Ok, I’ll work on that bash script too.

**Comment by webdog** [comment]
@trevor-coleman I believe so, it was something I pulled down from `brew` awhile back

To keep the repo clean, maybe throw that bash script in a `/scripts` folder for clarity sake? Thanks for the help!

**Comment by trevor-coleman** [comment]
@webdog To make the script work I had to grab the octicons package from npm.

It might make sense to have the script as a separate repo. Since there are a lot of options/documentation for the script.

I've put it up here for now if you want to take a look: https://github.com/trevor-coleman/render-octicons

**Comment by webdog** [comment]
>It might make sense to have the script as a separate repo. Since there are a lot of options/documentation for the script.

Rad! Thanks for keeping it as a fork 🙌 

Closing for now 😺
